name: Mutation Tests

permissions:
  contents: read

on:
  push:
    paths:
      - '**.php'
      - .github/workflows/mutation.yml
      - composer.json
      - infection.json5
      - phpunit.dist.xml
  pull_request:
    paths:
      - '**.php'
      - .github/workflows/mutation.yml
      - composer.json
      - infection.json5
      - phpunit.dist.xml

env:
  DEFAULT_PHP_VERSION: '8.5'

jobs:
  main:
    name: Check Code Quality with Mutation Testing
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ env.DEFAULT_PHP_VERSION }}
          tools: composer
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_DIR }}
          key: composer-${{ env.DEFAULT_PHP_VERSION }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ env.DEFAULT_PHP_VERSION }}
            composer-

      - name: Install dependencies
        run: composer update --ansi

      - name: Run Infection Mutation Testing
        run: composer mutation:check -- --ansi
        # env:
        #   INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}
